#%%
from base64 import encode
import json
import json
import re
import spacy


import sys
sys.path.append("../../src")
sys.path.append("../../scripts")

#from data_filepaths import s2_setFamilles
from data_filepaths import s2_setPrenoms
from data_filepaths import s2_setFamilles

#%%
"""
Création des sets de prénoms et de noms, 
on rajoute les nom au fur et à mesure puis on les mets en minuscule,
et les classe par ordre alphabétique
"""

#%%
listDePrenoms = ['Abondio','Abram','Abramo','adelaide','Adelajde','Agostin',
    'Agostino','Agnese','Alberto','onofrio','gottardo','gerardo',
    'Alessandro','Allessandro','stazio','moise\'','vetore',
    'Almorò','Alvise','alteniero','Ambrogio','adriano','tiberio',
    'Andrea','Andreina','Andriana','andrianna','angeglo','Angela','Angelo',
    'Anna','Anselmo','Antonia','Antonio','Apolonio','apollonio','Ascanio','Aurelio','Baldassare',
    'Bartolomeo','Basilio','Battista','Benedeto','Benedetto','benetto','bernardin',
    'Bernardino','Bernardo','Bertolo','Bertucci','Bertazzi','Bertuzzi','Benizio',
    'Biaggio','Bianca','Bortolameo','gregorio','angelica','venturino',
    'Bortolo','bartolameo','Bortolomeo','Bortolomio','bartolamio','Camilla','Camillo',
    'Carlo','Cattarin','Caterina','Catterina','Cecilia','Cesare',
    'Chiara','claudio','Contarina','Coriolano','Cornelia','Costantin',
    'Costantino','cristina','Cristoforo','Daniel','Daniele','David','Davide',
    'Domenica','Domenico','eleonora','Elena','almerigo','arcenio',
    'Elisabetta','Elisabeta','Elisazio','Ellena','emanuele',
    'Emanuel','Enrico','fabbio','Fabio','Faustino','appostolo',
    'Federico','Federigo','Felice','Ferdinando','Filippo','ridolfo',
    'Flaminio','Fortunato','Francesca','raimondo','anastasio',
    'Francesco','franco','Gabriel','Gabriele','Gabriella','Gaetano','Gaspare','Gasparo','Gerolamo',
    'Giacinto','Giacomo','Gio.Batta','Gioachino','mariano','alfonso',
    'Giorgio','Giovanna','Giovanni','GIrolamo','Girolamo','Giulia','Giulio',
    'Giuseppe','Giuiseppe','Giustina','Giustiniana','Giusto','Ignazio','Illustrissimo','Isabella','Laura','Lauro',
    'Lazaro','Laonardo','Leonardo','Leone','Lin','Livio','mandolin',
    'Lodovica','Lodovico','Loredana','silvano','ottavian','beltrame',
    'Lorenzo','Luca','Lucca','lucio','Lucia','Lugrezia','Luigi',
    'Maddalena','Madalena','marcella','Marcello','Marianna','MarcAntonio','marc\'antonio',
    'Marco','Maria','Mariana','marietta','Mario','Marin','Marina','Marino',
    'Margarita','Margherita','Marta','Matteo','Mattio','Michiel','michiele',
    'Michele','Michielle','morella','natalino','Nicoleto','nicoletto',
    'Niccolò','Nicolò','olivo','Onorio','Orsola','Ottaviano','Ottavio',
    'Orazio','Osvaldo','Paolina','Paolo','Pasin','Pasquale','Pasqualino',
    'Paulo','perina','piero','Pietro','Pisana','Polisena','Polissena','Raffaele',
    'Regina','Rinaldo','Rizzardo','Roberto','Rocco','romana','lucrezia','spiridon',
    'Rosa','sadia','Salamone','Salomon','Salomone','Salvador','salvatore','Samuele','Santo','Sebastian',
    'Sebastiano','Serafina','Silvestro','Simeone','Simon','Simone',"michel'angelo",
    'Soranzo','Stanislao','Stefano','Steffano','Teodoro','melchiore','bortolo',
    'Teresa','Tomaso','Tommaso','Valentin','Valentino','Vettor','zacaria',
    'Vettore','Vido','Vincenza','Vincenzo','Vita','Vitale','Vittoria','vitore',
    'Vittore','Vivante','Zaccaria','Zuanne','gianfrancesco','emanuelle','maffio',
    'reniero','carolina','demetrio','speridion','spiridion','spiridione','capello',
    'sabbato','leonara','lunardo','lavia','michee','guido','michel','micchel',
    'lazzaro','giuseppa','arturo','isidoro','costante','adriana','fedrico','pellegrin',
    'annibale','nunzio','nuncio','brigida','tranquillo','veronica','vito','guglielmo',
    'pasqua','giacobe','michelangelo','giovavanni','clemente','gisacomo','pacifico',
    'amadeo','sigisberto','spiridone','giusepp','guseppe','baldissera','donato',
    'giovana','alesandro','sedecia','abundio','giancarlo','tadeo','benvenuto',
    'vitor','inocente','santa','vittorio','cizisberto','baldissere','biasio',
    'danielle','fardinando','ancillotto','girardo','matilde'
    ]

listDePrenomsLower = [x.lower() for x in listDePrenoms]
setPrenoms = sorted(set(listDePrenomsLower))

print('setprenom : ', len(setPrenoms))

listDeFamille = [
    'Acciajoli','Acerbi','ACQUISTI','Acquisti','Aglina','AGOSTINI', 'ALBEREGNO',
    'Alberghetti','ALBRIZZI','Albrizzi','ALESSANDRI','ALIPRANDI','AMADEI','AMOROSI',
    'ANCILLO','ANCILOTTO','Andrighetti','Andrioli','ANDRIUZZI','ANGARAN','Angaran',
    'ANGELONI','Angeloni','ANSAIZIO','Ansorsio','ANTONELLI','ARMANI','ARMATI','ARME','Aron',
    'ARRIGONI','ARTELLI','Artiga','ASTORI','Astori',
    'ASTORIE','AVANZETTI', 'AVESANI','BACANELLO','Bacchi','BACCOLO','Bachi',
    'BADAELI','BADIN', 'BADOER','BADOVER','Bagatella','BAGLIONI','BAGOLIN',
    'BALBI','BALDI','Baldi','BALLOTTA','Bana','BARBARIA','BARBARIGO','Barbarigo',
    'BARBARO','Barbaro','BARBERI','BARCELLI','Bardini','BARETINI', 'BARONCELLI','BARONCELLO','Barsella',
    'BASINELLO','Bassaglia','BASSI','BASTON','BATAJA','Bataglia','BATTAGLIA','BEGNIA',
    'Belfi','Bellati','Bellemo','BELLI','Beloto','Beltrame',
    'BELTRAMELLI','BELUVICH','BEMBO','BENEDETTI','Benetti','Benzon','BERABO','BERCO','BERETELLO',
    'BERENGO','BERLENDIS','Berlendis','Berlevi', 'BERNARDI','Bernardi', 'BERNARDO','Bertacina','BERTI','BERTOTTI',
    'BETTINI','Bettini','BIANCARDI','Bianchini','BIANCONI','BIASIUTI','Biasuti',
    'Bigaglia', 'BISCHUCHIA',
    'BISCUCCIA','BISSANO','BOCCHIALI','BOCHI','BOLANI','Bolani','BOLDU',"BOLDU'",'BOLINI',
    'Bolini','BOLLANI','Bollani','Bollini','BOMBA','Bonagrazia','BONE','BONETTI','BONFADINI',
    'BONLINI','BONVECCHIATO','Boraleri','BORGHESALI','BORINA','BORINI','BORIO','BOSIO','BOSSI','BOZZO',
    'BRAGADIN','Brandolina','Braoeti','Braveti','Brazzi','BRESCIANI','BRUSACERAME','BRUNELLO',
    'BULI','BUSETTO','BUSI', 'BUSIDA','Bustasi','Butacalize', 'Bembo', 'Bevilacqua',
    'Bolani','Boloni','Bon','Bontempi','Borina','Bortoli', 'Bragadin','Braider','Branchini',
    'Burati','Busacherin', 'Businello','CABIANCA', 'CABRINI','Cadorin','CAFFARI','Cagliari','CAGNINI',
    'CALBO','CALICHIOPOLI','CALVI','CAMOZZO','CAMPEIS','CANAL','CANALE','CANESTRARI',
    'CANNAL','Cannal','CANSIAN','CANZIANI','CAOTORTA','CAPELLAN', 'CAPELLO',
    'Capello','Capitanachi','CAPRA','Capretta','Capuzzo','Caretti',
    'Caricchiopoli','Caripimi','CARISSIMI','CARLI',
    'CARMINATI','CARRISSIMI','CARTELLI','Carvaglio','CASATTI', 'CASSETTI','CASTELLI','CATTARI',
    'CAVALLARI','CAVALLARO','CAVALLI','CAVOCO','CAZZATI','CENTENARI','CERONI',
    'CESER','CHERUBINI','CHINCHIO','CHINETTI','CHIRIBIRI','CHRICH','CIATTO',
    'CITTELLO','CLEMENTI','CODEMO','COLADARO','COLALTO','COLEDANI','COLETTI','COLLEDANI',
    'COLOMBO','COLONDA','COLOTTI','COMELLO','COMICCIOLI', 'COMINOTTO', 'CONDULMER','CONFURTUNATI',
    'CONOMO','CONTARINI','CONTI', 'CONTINI', 'COOK','COREDANO','CORNELIA', 'CORNER',
    'CORNERA','CORONA','CORRER','COSTANTINI','COTTONI', 'CRIVELARI','CROTTA','Calvi',
    'Capelari', 'Cardazzo', 'Casolo',
    'Catullo', 'Cavallaro', 'Compagnia', 'Contarini', 'Contini','CRUCIS','CURNIS', 'DALASTA', "DALL'ASTA",
    'DALLASTA', 'DANDOLO', 'DARIVA', 'DIEDO', 'DOLFIN','dolfini', 'DOLZE', 'DRIUZZI', 'DUODO',
    'Driuzzi', 'Emo','FABBRO', 'FOSCARINI', 'FOSCARINI', 'FRANCESCHI', 'FRANCOVICH',
    'FRANCOVIK', 'Foscari', 'Francesconi', 'GIOVANELLI', 'GIUSTINIAN', 'GRADENIGA',
    'GRADENIGO', 'GRIMANI', 'GRIPUTO', 'GRITTI', 'Gambillo', 'Garganego', 'Gazato',
    'Ghidoni', 'Girardi', 'Giuradelli', 'Grandis', 'Grassi', 'Grimani',
    'Griti', 'Guerra', 'Guidoni', 'LABIA', 'LIPOMANO', 'LISCHIUTA', 'LOREDAN',
    'LUCCATELLI', 'Loschi', 'Lucatello', 'Luzzato', 'MAFFEI', 'MAINARDI',
    'MANOLESSO', 'MARCONI', 'MARINI', 'MARTINENGO', 'MEMO', 'MICHELI', 'MOLIN',
    'MORA', 'MORETTI', 'MOROSINI', 'MOZENIGA', 'Magno', 'Malipiero',
    'Manca', 'Manfrin', 'Marzan', 'Mazzuccato', 'Mensurati', 'Michieli', 'Minelli',
    'Mocenigo', 'Mora', 'NANI', 'Namias', 'Ottoboni', 'PERAZZO', 'PESARO',
    'PISANI', 'PORTO', 'PRIULI', 'Parenzo', 'Perlasca', 'Pizzamano', 'Poro',
    'RAZINI', 'RENIER', 'RIGONI', 'RIVA', 'Rampinetti', 'Renier', 'Rezzonico', 'Rizzi',
    'Rotta', 'Rubelli', 'Rucini', 'SALLA', 'SANDI', 'SANTONINI', 'SAVARDINA', 'SAVOLDELLO',
    'SODERINI', 'SOLARI', 'SORANZO', 'SPIGA', 'SPINELLI', 'SUDARINI', 'Sandi', 'Sansoni',
    'Sapella', 'Savaldello', 'Solari', 'Stella', 'Sulam', 'TASCA', 'TODESCHINI',
    'Toderini', 'Todeschini', 'VALARESSO', 'VALIER', 'VENDRAMIN', 'VENIER', 'VISCOVICH',
    'Valvason', 'Vendramin', 'Vitturi', 'Widman', 'ZAMFERMO', 'ZAMPIERI', 'ZANFERMO', 'ZEN',
    'ZENOBIO', 'ZINELLI', 'ZOLIO', 'ZOLIO', 'ZON', 'ZUCCATO', 'Zamparo', 'Zampiceli', 'Zanbelli',
    'Zechinato', 'Zon', 'Zuanne',
    'Castelli','Catani','Cavazza','Ceponi','Cera','Cerotti','Chiaraba','Chichisiola','Chimotto',
    'Chioelolo','Cisi','Ciuran','Civran','Clario','Clementi','Clementi','Coen','PORTO','Porto',
    'Colombo','Combi','Comello','Comina','Contarini','Conti','Contin','Cornelio','Corner',
    'Cornioli', 'Correggio','Correr','Corticelli','Cossovik','Costantin','Costantini','Cressini',
    "D'ALEZE","D'Altin",'DABEMI','DALEZE','DAMEZZO','DARDI','DARIGO','DARIN','DATORTA','DELASIA',
    'DELOTTO','DENTE','DEPORTES','DESANDOVIK','DESERPOS','DIAMANTINI','DIEDO','DOLCE',"DONA'",
    'DONADA','DONADONI','DORIA','DOSMO',"DOZERA'",'DUJA','Dabonte','Dalpeder','Danieli','Daponte',
    'Darin','Dario','Dente','Deventura','Dipieri','Dolfin',
    'ABIS','ANDREGHETTI','ANGELI','ANSOISSIO','ARMENI','AZAMAR','Albengo','Alberti',
    'Avanzi','BALLARINI','BANE','BARBIERI','BASEGGIO','BASEGIO','BATAGLIA','BELLOTO',
    'BENZON','BERTANI','BERTEN','BEVILACQUA','BONADEI','BONI','BONTEMPI','BORELLA',
    'BORGHETTI','BOTOLI',"BRACHE'",'BRAGATTO','BUTACALIZE','Baroncelli','Battaglia',
    'Beltramelli','Berti','Biasiuti','Bonicelli','Borin','Bosio','Bossi','Breda',
    'Bulo','CANNONICI','CARESANA','CARETTA','CAROBOLI','CARRARA','CASSINI','CATTANEO',
    'CIATO','CICELLI','CIVRAN','COCO','COLUZZI','COMAROLO','COMBI','CORNOLDI','CRIVILIER',
    'CRUCIJ','Canal','Caotorta','Carer','Castelli','Celini','Cenagin','Ceriman','Ciatto',
    'Cobres','Coledani','Corregio','Curiel','DADA','DAMULA',"DARI'",'DATOSCHI','DAVIDE',
    'DEBEI','DELAI',"Dall'Asta",'Damiani','Donadoni','Duce','Duodo','EMO','ERIZO','ERIZZO',
    'Erizo','Erizzo','FABRIIS','FABRIS','FALLIER','FARINELLA','FARSETTI','FAVRETTI',
    'FEDRIGO','FELTRONI','FERRARI','FERRETTI','FERRI','FILIPPI','FILIPPINI','FILLIPPI',
    'FINI','FIOLETTI','FIOLOSSO','FLANGINI','FLORIAN','FOGAROLI','FONDA','FONTANA',
    'FONTANELLA','FORATI','FORESTI','FORLICHE','FORMENTELLO','FORTUNATI','FOSCARI',
    'FOSCOLO','FOSSATI','FRANCESCONI','FRANCHI','FRANCHINI','FRANCO','FRANGINI',
    'FRATTINI','FRUCCO','FUMAGALLI','FURLANETTO','Fabian','Fabris','Fabro','Falier',
    'Faoretto','Fassioli','Faustini','Ferrari','Ferri','Ferro','Filetto','Filippo',
    'Fini','Florian','Foker','Fontana','Foscarini','Fovel','Fracassetti','Fracassetti',
    'Franceschi','Franchini','Franzini','Franzo','Franzoni','Frisan','Furian','GABRIELI',
    'GALANTE','GALAZZi','GALINO','GALIUTI','GALLI','GALLINO',"GALLIU'",'GALLO','GAMBELLO',
    'GAMBILLO','GARGANEGO','GARLATA','GARLATO','GARZONI','GASPARI','GASPARINI','GASTALDI',
    'GAUDIO','GELMA','GENARO','GHEDINI','GHERARDINI','GHERO','GHESI','GHEZI','GIANDOLINI',
    'GIANOTTI','GIDONI','GIORDANI','GIOVICH','GIRARDI','GIULI','GIULLI','GIURICH',
    'GIUSTINIANI','GOTTONI','GRANDIS','GRAPIGLIA','GRAPUTO','GRASSI','GRIFALCONI','GRIS',
    'GROLA','GUARNIERI','GUAZZO','GUELLACASA','GUERINO','GUERRA','GUERRA','GUIZZETI',
    'GUIZZETTI','Galante','Galdi','Galizzo','Gambino','Garbin','Garlata','Garzador',
    'Gaspari','Gavardini','Gavazzi','Gedin','Gennaro','Gentili','Ghero','Ghezzi',
    'Ghislanzoni','Gianzik','Giarca','Giavallin','Gieppi','Giovanelli','Gislanzoni',
    'Giupponi','Giustinian','Giustiniani','Gobbi','Gradenigo','Grapini','Gratarol',
    'Grava','Greco','GriFalconi','Gripogono','Gritti','Guarinoni','Guarnieri','Guidoti',
    'Guizzetti','INSON','IVANOVICH','Indri','LABBIA','LAMBERTI','LANFRANCHI','LANFRITO',
    'LANFRITTO','LANTERNA','LANZA','LAVEZARI','LAVEZZI','LEANDRI','LEZZE','LICINI','LIO',
    'LODOVICI','LOGIATO','LOMBARDI','LOMBARDO','LONGO','LOREDANO','LORENZON','LORIS',
    'LOVISONI','LUCATELLI','LUCATELLO','LUCCATELLO','LUDOVICI','LUGO','LUZZATO','LUZZO',
    'Labia','Lanterna','Latacchi','Licini','Licini','Lioni','Lipamano','Lollo','Longo',
    'Loredan','Lovisoni','Lucatelli','Luisello','Luvisello','Luzato','Luzzo','MACARUZZI',
    'MADERNI','MAFEI','MAGNO','MAGRO','MAISETTE','MALANOTI','MALANOTTI','MALIPIERO',
    'MAMBRIM','MANDER','MANETTA','MANETTI',"MANFRE'","MANFRE'",'MANFREDINI','MANOLEZZO',
    'MANTOVANI','MANZOLI','MANZONI','MARCATI','MARCELLA','MARCELLO','MARCELO','MARCHESINI',
    'MARCHI','MARCOVIK','MARIN','MARIONI','MARTIN','MARTINELLI','MARTINOLI','MARTINUSSI',
    'MARUZZI','MASCAROL','MASTINI','MATTIUZZI','MEDUN','MERLINI','MERLO','MICHIELI',
    'MILESI','MINIA','MINIO','MINOTTI','MIPRANDI','MISSANA','MIZZANA','MOCCHI','MOCENIGO',
    'MOLARI','MOLINARI','MOLINI','MONDINI',"MONFERA'",'MONICI','MORO','MORONI','MOZENIGO',
    'MOZZI','MUSITELLI','MUSOLO','MUZZATO','Macaruzzi','Macer','Maderini','Maderni',
    'MaestRizzi','Magrini','Majer','Malimpiero','Malta','Malveti','Manasangue','Manezzi',
    'Manin','Manolesso','Manzoni','Maratti','Marcalion','Marchesani','Marchesini',
    'Marchetti','Marchi','Marcovik','Marin','Marinello','Marini','Marioni','Marsili',
    'Martello','Martinelli','Martini','Maruzzi','Marzello','Marzola','Massa','Mastini',
    'Melchiori','Meneguzzi','Mestre','Milik','Milla','Minich','Minotto','Mizzana','Molena',
    'Moleti','Moli','Molin','Monti','Morati','Moro','Moroni','Mozenigo','Mozzi','Murer',
    'NADALI','NADO','NALON','NANETTI','NARDI','NARDINI','NASOLIN','NEGRELLO','NEGRI',
    'NENNI','NICOLI','NINFA','NODOLI','NOSADINI','NOVELLO','Nani','Nani','Negrelli','Negri',
    'Negroni','Nerini','Nicoli','Nosadini','Nosadini','Novello','OGLIENI','OLIVI','OLIVO',
    'OLMO','ORIO','ORLANDI','ORTALLI','Olivi','Olivieri','Olmo','Omigoni','Orio','Orsoni',
    'Ottolin','PADOVAN','PADOVANI','PAGAN','PAGANELLO','PAGANI','PAGINI','PANAGIOTTO',
    'PANEINFORNI','PANIGAI','PANZIERA','PAOLINI','PAPETTE','PASETTE','PASOTTI','PASQUALIGO',
    'PASQUALIN','PASSAMANER','PASSI','PASTA','PASTORI','PAVAZZA','PAVOLI','PAZINI','PAZZI',
    'PEDROCCHI','PEDROCCHI','PEDROSIN','PELANDINA','PENERINI','PERAZOLLO','PERINI','PERSEGO',
    'PERSICO','PERUCHIN','PETROGALLI','PETROVICH','PETROVICH','PEZZANA','PEZZATO',
    'PEZZI','PEZZOLI','PIANELLA','PIASENTI','PIATI','PIATTI','PICAZZO','PICCARDI','PICCIOLI',
    'PICCOLI','PISONI','PIZONI','PIZZAMANO','PIZZORDINI','PLATEO','POCCOBELLI','POLESE',
    'POLICE','POLICI','POLISE','POLLI','PONTE','PORTA','POZZI','PREMUDA','PREZZATO','PROVEDAN',
    'PUGNALETTO','PUGNALIN','PUZZETTI','Pace','Padovan','Paganello','Palazzi',
    'Palese','Panciera','Panocchia','Pantanali','Papafava','Paseti','Pasqualigo','Peccenini',
    'Pedrocchi','Pelegrini','Perasciuti','Perosa','Piaja','Piatti','Pico','Pignola','Pilizioli',
    'Pinaffo','Pinato','Pizioli','Plendini','Polacco','Polaco','Polese','Poli','Pora','Pori',
    'Porta','Posani','Potima','Pretti','Priuli','Pugiato','Pugnaletto','Pupilli',
    'QUERINI','QUONDANSI''Querini','RAFFAI','RASPI','REALI','REGIO','REMONDINI','REMPS',
    'REZZONICO','RICCOBONI','RIGAMONTI','RIGHI','RIGO','RINALDI','RINALDO','RISEGATI','RIZZARDI',
    'RIZZETTI','RIZZI','RIZZO','ROBINI','ROBUSTELLO','ROCCHETTA','ROGGIA','ROSADA','ROSADA',
    'ROSSI','ROVELLI','ROVI','RUBBI','RUBELLI','RUGGIA','Raffai','Ragazzi','Rampinelli','Raspi',
    'Ratti','Reali','Regolise','Ricane','Rigo','Riscetti','Rizzardini','Rizzo','Robustello',
    'Roggia','Rogia','Romanello','Rombenghi','Rosada','Rossetti','Rossi','Rubini','Rumieri',
    'SACATO','SADALI','SAGRAMORA','SAGREDO','SALAROL','SALERALI','SALVI','SANFEROMO','SANUDO',
    'SAPELLA','SARTORI','SASSELLO','SASSO','SCAGIO','SCALABRINI','SCALFAROTTO','SCARELLO',
    'SCOFFA','SCORELLA','SCOTTI','SCUDELARI','SEDEA','SEGATTI','SELICH','SEMITECOLO','SEORDIGLI',
    'SERA','SERATO','SERIMAN','SERO','SERPE','SERRA','SIEDEA','SILVESTRINI','SIMIONATO','SIRMEN',
    'SOARDI','SOPERCHI','SPIRITO','SPONZA','SQUADRONI','STAE','STAVIGNONI','STECHINI','STEFFANI',
    'STELLA','STRATI','STRUCA','SVARIO','Sabbia','Sagramora','Sagredo','Sala','Salaman','Salci',
    'Salla','Salvadori','Salvini','Sanchi','Sansonio','Sanzonio','Saraval','Sardi','Sartori',
    'Scalabrin','Schiantarello','Sedea','Sepora','Serafini','Seraval','Seriman','Seriman','Serno',
    'Sesia','Settimini','Settini','Simoni','Sisconi','Sorari','Spinelli','Stai','Stefani','Steffani',
    'Sullam','Svario','TACCO','TAMBELLI','TAOLIN','TARABOCCHIA','TENESCHI','TERAZZINA','TETTAMASI',
    'TIEPOLLO','TIEPOLO','TIOSSI','TIRINKAN','TOBIA','TODARINI','TODERINI','TOGNANA','TOLOMEO',
    'TOMASINI','TOMMASINI','TONCI','TONETTI','TONIATO','TONINI','TONON','TORRACULI','TREMIGNORI',
    'TRENTINI','TREVISAN','TREVISANI','TROMBE','TROMBETA','TRON','TRUSIS','TURBIN','TaManina',
    'Tabacchi','Tabboga','Tagliapietra','TamAI','Tarabocchia','Targa','Tassioli','Tazzioli','Terni',
    'Tirabosco','Tironi','Tobia','Todesco','Toffolutti','Tognana','Togniana','Tomasi','Tomasini',
    'Ton','Tonon','Tovanovich','Traversi','Trentin','Trentini','Trevisan','Trevisan','Trevisana',
    'Trevisani','Trifoni','Tron','Tuschetto','Usabel','VACILLI','VALENTINI','VALLIER','VALMARANA',
    'VALMARANA','VARDA','VARISCO','VARRINI','VENDRAMINA','VENDRAMINI','VERONA','VEVRINI','VIANELLO',
    'VIANELLO','VIATO','VIDO','VIGENTINI','VIGNOLA','VIOLA','VIRCOVICH','VISCIUTA','VISICH','VISICH',
    'VISIK','VISILICH','VITALI','VITTURI','VIZENTINI','Valentini','Vasilicò','Vecil','Veludo','Venier',
    'Ventura','Venturali','Verasso','Verdi','Vernisi','Veronese','Vesci','Vetturi','Vezzi','Vianello',
    'Vianni','Vidiman','Violin','Violina','Visentini','Vitali','WIDMAN','WIDMANN','ZAGARI','ZAGURI',
    'ZAMBELLI','ZANI','ZANIN','ZANINI','ZANNE','ZANOBRIO','ZANON','ZAPELLA','ZAPPELLA','ZATTI','ZEFIRI',
    'ZENARO','ZENNARO','ZENOBRIO','ZIGNO','ZIGNO','ZIRON','ZITTI','ZIUSTO','ZOCCHI','ZOLA','ZOPETTI',
    'ZORZI','ZUANICHI','ZUARATA','ZUCATO','ZUSTO','Zambelli','Zampiceni','Zampiceni','Zampieri',
    'Zanchetta','Zanchini','Zane','Zanetti','Zangarofoli','Zannon','Zanon','Zanuto','Zanutta','Zeberlin',
    'Zen','Zino','Zitti','Zocchi','Zorzetto','Zuccato','Zuliani','QUONDANSI','Querini','condolmer',
    'trieste','farelli','mosini','morosini','barbon','bondoner','bonali',
    'lucchesi','caliari','kromer','gradenigo','fantinelli','zoccolo','stecchini',
    'toffetti','leccini','bonagli','rugeri','filosi','concina','corniani','bovicini',
    'testa','accerboni','pasco','sabioni','lino','giupponi','agazzi','lazzari','malipiero',
    'monticano','piccoli','pepoli','baldovini','veronesi','giupponi',
    'gritti','foscarini','vacilli','lio','mastini','berengo','belloto',
    'molini','galino','minio','gallino','rinaldo','pagini','magro','caroboli',
    'grifalconi','ancillo','crucij','lio','venier','guerra','priuli',
    'nani','zaguri','fontanella','steffani','fanelli','bravo','manini','malipiero',
    'vanentgardenn','benzoni','turchetto','riva','miani','giovannelli','grotto','peruli',
    'giuponni','monticano','fisser','gambiosi','marzolo','carminati','terracina','angaran',
    'zustinian','giustinian','recanati','pisana','longo','minelli','rota','mocchi',
    'corner','moroni','fanelli','pussi','brini','lazari','zanenghi','iacour','tassis',
    'formenti','tasca','bao','sulan','fonte','bardese','pinton','fagioto','livan','faliva',
    'fortunio','mazzochi','lio','trevano','pazienti','giviani','zorzi','saloon','pinoli',
    'girardini','bragadini','sopai','rocchi','acerboni','lionello','vanesta','gardinali',
    'savi','sossai','asprea','alcaini','bertignazza','gasparoni','cavenago',
    'gramolin','gagio','stiore','ponga','tronconi','penso','degna',
    'volpi','pellegrini','capellis','bordini','cussetti','alghisi','grotta','cremona',
    'ambrosi','fazandella','tanxik','ragasin','lavezzari','capparocca','grollo','luzziato',
    'demezzo','lion','gavazza','dosi','sanudo','monteso','sorzetto','sangian','ranier',
    'widiman','lardoni','zalvani','rede','basadonna','settemini','marangoni','pisella',
    'vituri','savioni','pivoli','versori','pele','trovisan','lambranzi','vivante','leoni',
    'azzoni','calliari','pedretti','modon','gasparotti','rossini','donati','orsato',
    'dabala\'','pelizioli','padoan','fossa','fidati','battagia','deputez','gheltof',
    'dondiorologio','michielli','bagozzi','macacari','bonvicini','paolucci',
    'paulucci','bentivoglio','saler','maffetti','battaggia','petropoli','cappello','bellini',
    'paoluzzi','manera','zanutti','pinardi','muttoni','ravenna','ferazzi','domeneghini',
    'foccacia','ghenisaghero','armano','baglione','sanfermo','busca','lione','polverini',
    'vattielli','bona','provini','marcellini','stuzio','galli','grolo','tofetti','forte',
    'moscheni','fedelli','bianza','recanatti','sodarini','podroizzer','rubi','schievano',
    'pighetti','moreto','fonsa','ferazzina','moretta','corti','faci','manfre\'','savrano',
    'lolin','crussi','zecchini','adami','calogera\'','pigazzi','vovo\'','racanati','palma',
    'venerando','raccanati','rubin','patella','pigozzo','guizetti','berretta',
    'cantoni','baretta','ruzzini','razzini','bellavita','passerina','vcelli','ghigi','bosato',
    'marzinoli','zandinelli','coreggio','psaus','benici','aguisti','martinego','merendis',
    'checcia','imson','carlin','trafego','cranz','bonzio','marinengo','bertignaza','aquisti',
    'morosin','gerardi','ravagnin','gerlin','gerlini','dadda','guardani','maffioletti',
    'zustiniani','giatti','ferutti','urbani','crascini','tosdechini','zorzi','giaccometti',
    'pavani','mauro','spangher','marino','sanchetta','zannini','visetti','wittmaan','falconi',
    'sopetti','pasquali','savorgnani','michiel','ottavian','beregan','ferrarioni','zancolo\'',
    'pavegio','candoni','casati','crovato','proto','fereti','bullo','bradamante','lovisello',
    'sensato','albinoni','puliti',"buldu'",'alessio','levi','ferarin','giusto','pedoni','crivelli',
    'gregorino','topi','giacomuzzi','zifra','ruffini','marzorati','conto','barazzutti','lian',
    'crescini','bissoni','storti','seles','duli','solimbergo','gruer','rafai','venerio','calvo',
    'giustiniano','biasutti','quarti','rizzotti','sangiantoffetti','lacciadelli','rugia','panziero',
    'marcolin','lucciadelli','torre','quadri','morilbatto','gardani','tognolo','tognollo','toniollo',
    'gabrini','paruta','piuco','foretti','giorgula','caldonazzo','azemarel','fava','monticana','ortali',
    'mongiat','busella','minopoli','bada','biondetti','mandelli','bettio','fedeli','capellari','vicelli',
    "cantu'",'taboga','suppies','lantana','vanest','burinello','rombenchi','mortari','perini','cavagnis',
    'folin','gerardini','dalcqua','chiodo','loccatelli','fascini','resaro','dapazze','gavardo','tornieli',
    'dona','vassilli','basili','giacutti','maifette','gini','gargadori','facchi','casalari','sipioni',
    'bandiera','codognato','fadiga','bozzi','voderini','basido','pestina','mostari','savorgnan','liccini',
    'scipioni','grllo','giuzzetti','talia','grimaldi','garzadori','basida','caminarovik','bravetti',
    'cortinovis','faseuri','simitecolo','zagher','biscuchia','crota','pesenti','biretti','trevisa','bressa',
    'rocchetti','squarzina','signoreti','taraboto','tassini','andrigheti','albergoni','mazzoni','mingoto',
    'ussemphumer','zanardi','zuccani','salon','fracasso','rublo','carraro','barcella','lorenzi','tan',
    'gregolin','arnaldi','rusteghello','boccacini','montanari','volpato','vessil','boscovich','scarizza',
    'barziza','isella','peruta','dionisio','marchiori','roder','zanuti','poloni','ongaro','nardo','verini',
    'gianolla','gianola','bertoti','gorgato','tamagno','malosso','lucatello','zanchi','marcheti','perotin',
    'catonari','bonomio','simonato','trento','passati','zochi','muchiachion','bujovich','rame','alessandrini',
    'boldrin','cavalieri','vettori','corena','barati','scarselini','toaldo','benetasso','baccanello',
    'mengato','picoli','zanardini','lucchese','antoniassi','varnier','vernasobre','bianchi','soprana',
    'calichipoli','manzini','pelai','beni','bisson','betti','cossetti','fiorin','ciera','pesodromo','nordio',
    'siola','cenarin','pachiasso','simoncin','marzari','dante','zavelli','crozzola','bonamin','gagieta',
    'calzavara','marcoleoni','peteno','gamba','formagin','salce','darduin','franceschini','bortolamiello',
    'parrocco','cardani','agnelleti','torni','lunigo','bonacini',"peteno'",'sografi','beneco','dalacqua',
    'gabardi','paron','chizzalli','coratelli','alpron','triffoni','rebelin','zappa','lotto','morellato',
    'chia','boromeo','bocarin','flamini','grisoldi','camerata','avanzeti','legrenzi','botti','marchesati',
    'morossi','iacur','vicentini','fannio','mosto','petaro','prioli','boldrini','rombiasi',"vlasto'",
    'milani','morcelli','basso','mosto','vanetti','vitalba','ribies','baraiter','fracasietti','scarella',
    'briani','maroni','acqua','barbetta','ferracina','revizzi','albini','giacchetti','soratroi','realdi','paneti',
    'pedrali','morbiotto','inion','demin','domeni','merlin','viali','penuta','florio','gheno','caregiani',
    'vallarezzo','giuliani','gianosovich','agnoletti','padella','favro','sbutega','angelini','glichi',
    "carita'",'tirroni','bussella','sapelli','marcatti','raffetti','duglia','niasa','bragatino','pieri',
    
    ]

listDeFamilleLower = [x.lower() for x in listDeFamille]
setFamille = sorted(set(listDeFamilleLower))

print('setfamille : ', len(setFamille))

with open(s2_setPrenoms, "w") as f:
    json.dump(setPrenoms, f)

with open(s2_setFamilles, "w") as f:
    json.dump(setFamille, f)

# %%
